# Generated by Django 4.0.4 on 2022-04-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_type',
            old_name='type',
            new_name='label',
        ),
    ]
